version: "3.1"
services:

  nginx:
    container_name: click_nginx
    image: nginx:alpine
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${APP_PORT}:80"

  php-fpm:
    container_name: click_php
    build: ./
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

  postgres:
    container_name: click_pgsql
    image: bitnami/postgresql:16-debian-11
    expose:
      - "5432"
    ports:
     - "${DB_PORT}:5432"
    # volumes:
    #   - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=${DB_USERNAME}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_DATABASE}